// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck

// prettier-ignore
declare namespace _ZoteroTypes {
  interface Prefs {
    PluginPrefsMap: {
      "translate.enabled": boolean;
      "translate.auto": boolean;
      "translate.maxChars": number;
      "translate.engineType": string;
      "translate.google.apiKey": string;
      "translate.bing.apiKey": string;
      "translate.bing.region": string;
      "translate.deepl.apiKey": string;
      "translate.deepl.useFree": boolean;
      "translate.custom.apiUrl": string;
      "translate.custom.apiKey": string;
      "translate.custom.model": string;
      "translate.ai.apiUrl": string;
      "translate.ai.apiKey": string;
      "translate.ai.model": string;
      "translate.ai.prompt": string;
      "translate.targetLanguage": string;
      "pdfParser.opendataloader.enabled": boolean;
      "pdfParser.opendataloader.tableEnable": string;
      "pdfParser.opendataloader.useStructTree": boolean;
      "pdfParser.opendataloader.timeout": number;
      "pdfParser.opendataloader.returnImages": boolean;
      "translate.cache.enabled": boolean;
      "translate.cache.maxSizeMB": number;
      "reader.bilingual.defaultMode": string;
      "reader.bilingual.concurrency": number;
      "readAloud.rate": number;
      "readAloud.voice": string;
    };
  }
}
